### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [mickaelbaron/mickaelbaron.github.io#2]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`2015-10-31-mes-applications-pour-travailler-sous.md`](https://github.com/mickaelbaron/mickaelbaron.github.io/blob/20e32cc60b07307b1accfb4eb3be461380e10db7/_posts/2015-10-31-mes-applications-pour-travailler-sous.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by mickaelbaron** [comment]
Hi,

Thanks for your feedback.

I fixed t-my blog post ➡️ https://github.com/mickaelbaron/mickaelbaron.github.io/commit/31208dce043e942c1554eb61a1f97e6ca0608dc7

Best,

Mickael
